### ISSUE TITLE
코드 피드백

### ISSUE THREAD

**Issue by woohm402** [thisisWooyeol/2048-game-in-web#1]
# 상수 사용 👍 

https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L23-L24

`rowLength`, `columnLength` 등 의미있는 상수 잡아주시는 거 좋습니다 👍 

<br/><br/>

# `useState` 초기값

https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L27-L32

`initialState` 가 매 렌더마다 계산될텐데 조금 어색한 감이 있습니다.

```ts
const [map, setMap] = useState<Map2048>(() => 
  loadGameState()?.map ?? resetMap(rowLength, columnLength)
);
```

이런 식으로, 초기값을 얻는 데에 함수가 필요하다면 `useState` 파라미터에 초기값을 계산하는 함수를 넣는 게 좀더 자연스럽습니다!

<br/><br/>

# `useState` 제네릭

https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L43

10월 2일 세미나에서 배우긴 할 텐데, 타입스크립트 자동추론이 생각보다 똑똑해서 이부분 제네릭은 없는 게 좀더 권장됩니다!

```ts
// 이거 대신
const [keyPressed, setKeyPressed] = useState<string>('');

// 이렇게
const [keyPressed, setKeyPressed] = useState('');
```

<br/><br/>

# 불필요한 `useCallback`

https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L46-L64

`newGameButton` 이 `useCallback` 으로 감싸질 필요가 없을 것 같습니다! (`useEffect` 의존성 배열에 들어가거나 하는 게 아니므로)

이에 따라 `newGameHandler` 도 `useCallback` 으로 감싸지 않아도 될 것 같습니다

바로 밑에 있는 `keyPressHandler` 는 감싸주신 거 좋습니다 👍 

<br/><br/>

# `useEffect` 의 잘못된 사용법

https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L66-L96

직전 세미나에서 `useEffect` 가 리액트 외부와 내부를 동기화시키는 훅인 것으로 안내드렸었는데, 지금은 리액트 상태와 상태 사이를 동기화하고 있기 때문에 안티패턴이고 실제로 `useEffect` 를 제거할 수 있습니다.

지금 이렇게 되어 있는데,
1. 키가 눌릴 경우 눌린 키를 상태에 저장한다
2. 상태에 저장된 키가 변경되면 이펙트가 트리거될 것이다
3. 트리거된 이펙트에서 새로운 map 상태를 계산해서 업데이트한다

훨씬 간단하게 가능합니다.
1. 키가 눌릴 경우 새로운 map 상태를 계산해서 업데이트한다

그래서 원래는 `keyPressed` 상태도 없어도 되고, 저 `useEffect` 도 없어도 됩니다!

밑에 있는 [이 친구](https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L98-L100)도 마찬가지로 불필요한 이펙트입니다.

일부러 설명을 좀 추상적으로 드렸는데, 불필요한 이펙트를 제거하는 더 자세한 방법은 관련 [리액트 공식문서](https://ko.react.dev/learn/you-might-not-need-an-effect) 읽어보시는 걸 추천드립니다 :)

<br/><br/>

# `useEffect` 의 올바른 사용법 👍 

https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/App.tsx#L102-L104

반면 이 친구는 리액트 내부 (map, score, bestScore, gameStatus 상태) 와 리액트 외부 (localStorage)를 동기화하는 훅이므로 올바른 사용법이 맞습니다!

<br/><br/>

# 이외 마이너한 것들

- `React.FC` 는 잘 안 씁니다. 보통 컴포넌트 타입은 `const MyComponent = ({}: MyComponentProps) => {` 이런 식으로 선언합니다.
- [`getCellColor` 함수](https://github.com/thisisWooyeol/2048-game-in-web/blob/178793563ed6bc80bcf485249b8d9a4a87d0ef88/src/utils/Map2048.ts#L203)가 tailwind 에 결합되어 있어서 아키텍처적으로 좀 애매한 느낌이 있습니다! (가령 tailwind를 안 쓰는 결정을 하게 될 때, 이 부분 리팩토링을 놓치기 쉬울듯)
- 타입스크립트를 좀더 잘 활용해볼 수 있을 것 같은데 10월 2일 세미나 이후로 진행될 과제에서 더 개선해보셔도 좋을 것 같습니다!

**Comment by thisisWooyeol** [comment]
#2 덕분에 수정 반영했습니다. 상세한 피드백 감사합니다.🙇‍♂️
